### ISSUE TITLE
neural hawkes process

### ISSUE THREAD

**Issue by junhyk** [HMEIatJHU/neurawkes#2]
Hi
I'm interested in implementing your work in pytorch and use it in my personal project
I found your repo of your latest work, neural hawkes particle smoothing, 
and it seems using C-Lstm which is I guess the main part of neural hawkes process.

So is it really identical?
What part of NHPS is the original neural hawkes process?

Thanks

**Comment by hongyuanmei** [comment]
> Hi
> I'm interested in implementing your work in pytorch and use it in my personal project

Thanks for your interests! 
Sorry for the late reply, but I'd like to answer any questions you have for implementing it! 

> I found your repo of your latest work, neural hawkes particle smoothing,
> and it seems using C-Lstm which is I guess the main part of neural hawkes process.

Yes, you are right! 
 
> So is it really identical?

Part of it. 
The neural Hawkes particle filtering part is almost identical to the original NHP, because it requires a trained NHP. You can refer to the section-2 and -3.1 of this ICML paper https://arxiv.org/pdf/1905.05570.pdf for details. 

> What part of NHPS is the original neural hawkes process?

If you want to know which part of that codebase is exactly NHP, maybe you can leave questions there, so I can answer them and also revise my README accordingly? 

Or, maybe even more convenient for you, I have a PyTorch version of NHP that is not ready to release yet, but I am okay sharing it with you in person. So maybe you can send me an email if you'd like it? 
 
> Thanks

Thank you!

**Comment by tonygracious** [comment]
@HMEIatJHU  Can you share me the pytorch version NHP model? I have also send you a mail asking for the same.
